<?php
declare(strict_types=1);

namespace Got;

/**
 * Server configuration written by the installer to storage/config.php.
 * Holds the database connection details and the secret application key.
 */
final class Config
{
    private static ?array $data = null;

    public static function path(): string
    {
        return STORAGE_DIR . '/config.php';
    }

    public static function installed(): bool
    {
        return self::all() !== [];
    }

    public static function all(): array
    {
        if (self::$data === null) {
            $data = is_file(self::path()) ? require self::path() : [];
            self::$data = is_array($data) ? $data : [];
        }
        return self::$data;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        return array_get(self::all(), $key, $default);
    }

    /** Secret key used to sign form tokens and hash IP addresses. */
    public static function key(): string
    {
        $key = (string) self::get('app_key', '');
        if ($key === '') {
            throw new \RuntimeException('The site is not installed yet.');
        }
        return $key;
    }

    public static function write(array $data): void
    {
        $php = "<?php\n"
            . "// Generated by the GOT FITNEZZ installer on " . gmdate('Y-m-d H:i') . " UTC.\n"
            . "// Keep this file private: it contains your database password and secret key.\n"
            . 'return ' . var_export($data, true) . ";\n";
        $tmp = self::path() . '.' . bin2hex(random_bytes(4)) . '.tmp';
        if (file_put_contents($tmp, $php, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write the configuration file. Check that the storage folder is writable.');
        }
        @chmod($tmp, 0640);
        if (!rename($tmp, self::path())) {
            @unlink($tmp);
            throw new \RuntimeException('Could not save the configuration file.');
        }
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate(self::path(), true);
        }
        self::$data = $data;
    }

    /** Replace the in-memory configuration (used by tests and command-line tools). */
    public static function override(array $data): void
    {
        self::$data = $data;
    }
}
